import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import React from 'react';


const inter = Inter({ subsets: [ 'latin' ] });

export const metadata: Metadata = {
    title      : 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout (
    { children }: Readonly<{ children: React.ReactNode; }>,
) {
    return (
        <html lang="ru">
        <body className={ inter.className }>
        <header>
            <nav>
                <Link href={ '/' }>home</Link>
                <Link href={ '/about' }>about</Link>
                <Link href={ '/users' }>users</Link>
            </nav>
        </header>
        <main>
            { children }
        </main>
        </body>
        </html>
    );
}
